# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RealmJWTSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealmJWTSample
  pod 'RealmSwift', '~> 3.3.2'
  pod 'Eureka'
  pod 'Alamofire'
end
