{
 "title": "Realm Object Server Stats",
 "tags": [ "raas" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Log Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log Messages By Level",
   "type": "graph",
   "description": "The total number of log messages per minute",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Per Minute" }
   ],
   "targets": [
    {
     "expr": "sum by(level)(increase(ros_log_messages_total[1m]))",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Log Messages By Job",
   "type": "graph",
   "description": "The total number of log messages per minute, for all tenants",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Per Minute" }
   ],
   "targets": [
    {
     "expr": "sum by (component) (increase(ros_log_messages_total[1m]))",
     "legendFormat": "{{ component }}"
    }
   ]
  },
  { "title": "Sync Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Connections and Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(ros_sync_connection_online)",
     "legendFormat": "Connections"
    },
    { "expr": "sum(ros_sync_session_online)", "legendFormat": "Sessions" },
    { "expr": "sum(ros_sync_realms_open)", "legendFormat": "Realms Open" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{component=\"sync\"}[5m]))"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{component=\"sync\"})"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Transactions per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ros_sync_changeset_integrated[5m]))",
     "legendFormat": "Changesets Integrated"
    },
    {
     "expr": "sum(rate(ros_sync_download_constructed[5m]))",
     "legendFormat": "Downloads Constructed"
    }
   ]
  },
  {
   "title": "Event loop",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "ros_sync_event_loop_saturation", "legendFormat": "Saturation" },
    {
     "expr": "ros_sync_event_loop_inefficiency",
     "legendFormat": "Inefficiency"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "sum(ros_sync_disk_usage_bytes)", "legendFormat": "Used" },
    { "expr": "sum(ros_sync_disk_size_bytes)", "legendFormat": "Available" }
   ]
  },
  {
   "title": "Sync Protocol Transferred",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ros_sync_protocol_bytes_received[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(ros_sync_protocol_bytes_sent[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Connection terminations (cumulative)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(ros_sync_conn_term_end_of_input) +\nsum(ros_sync_conn_term_connection_reset_error) +\nsum(ros_sync_conn_term_broken_pipe_error) +\nsum(ros_sync_conn_term_system_error) +\nsum(ros_sync_conn_term_network_error) +\nsum(ros_sync_conn_term_ssl_error) +\nsum(ros_sync_conn_term_http_error) +\nsum(ros_sync_conn_term_websocket_error) +\nsum(ros_sync_conn_term_sync_protocol_error) +\nsum(ros_sync_conn_term_error_of_unexpected_category) +\nsum(ros_sync_conn_term_heartbeat_timeout) +\nsum(ros_sync_conn_term_http_response_written)",
     "legendFormat": "All"
    },
    {
     "expr": "sum(ros_sync_conn_term_end_of_input)",
     "legendFormat": "End of input"
    },
    {
     "expr": "sum(ros_sync_conn_term_connection_reset_error)",
     "legendFormat": "Connection reset"
    },
    {
     "expr": "sum(ros_sync_conn_term_broken_pipe_error)",
     "legendFormat": "Broken pipe"
    },
    {
     "expr": "sum(ros_sync_conn_term_system_error)",
     "legendFormat": "System error"
    },
    {
     "expr": "sum(ros_sync_conn_term_network_error)",
     "legendFormat": "Network error"
    },
    {
     "expr": "sum(ros_sync_conn_term_ssl_error)",
     "legendFormat": "TLS error"
    },
    {
     "expr": "sum(ros_sync_conn_term_http_error)",
     "legendFormat": "HTTP error"
    },
    {
     "expr": "sum(ros_sync_conn_term_websocket_error)",
     "legendFormat": "WebSocket error"
    },
    {
     "expr": "sum(ros_sync_conn_term_sync_protocol_error)",
     "legendFormat": "Sync protocol error"
    },
    {
     "expr": "sum(ros_sync_conn_term_error_of_unexpected_category)",
     "legendFormat": "Error of unexpected category"
    },
    {
     "expr": "sum(ros_sync_conn_term_heartbeat_timeout)",
     "legendFormat": "Heartbeat timeout"
    },
    {
     "expr": "sum(ros_sync_conn_term_http_response_written)",
     "legendFormat": "HTTP response written"
    }
   ]
  },
  {
   "title": "NodeJS Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_eventloop_lag_seconds{component=\"sync\"})"
    }
   ]
  },
  { "title": "Core Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "HTTP Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ros_http_bytes_received{component=\"core\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate(ros_http_bytes_sent{component=\"core\"}[1m])) * -1",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Total Active Sync Proxy Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ros_sync_proxy_active_connections{component=\"core\"})",
     "legendFormat": "Sync Connections"
    },
    {
     "expr": "sum(count by(identity)(ros_sync_proxy_active_connections{component=\"core\",identity!~\"__.*\"} > 0))",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(\n    process_cpu_seconds_total{component=\"core\"}[1m]\n))"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    process_resident_memory_bytes{component=\"core\"}\n)"
    }
   ]
  },
  {
   "title": "NodeJS Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_eventloop_lag_seconds{component=\"core\"})",
     "legendFormat": "Lag (s)"
    }
   ]
  }
 ]
}