{
 "title": "Sync Worker Groups",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "group",
    "query": "label_values(ros_sync_download_constructed_ms_bucket,group)"
   }
  ]
 },
 "panels": [
  { "title": "Sync Worker Group $group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "group" },
  {
   "title": "Online Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(ros_sync_session_online{component=\"sync\",group=\"$group\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(process_resident_memory_bytes{group=\"$group\"})\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(increase(\n    process_cpu_seconds_total{component=\"sync\",group=\"$group\"}[1m]\n))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Sync Worker Group $group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Online Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ros_sync_session_online{group=\"$group\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(process_resident_memory_bytes{group=\"$group\"})\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(increase(\n    process_cpu_seconds_total{component=\"sync\",group=\"$group\"}[1m]\n))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Sync Worker Group $group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Online Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ros_sync_session_online{group=\"$group\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(process_resident_memory_bytes{group=\"$group\"})\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(increase(\n    process_cpu_seconds_total{component=\"sync\",group=\"$group\"}[1m]\n))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Sync Worker Group $group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Online Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ros_sync_session_online{group=\"$group\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(process_resident_memory_bytes{group=\"$group\"})\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 14, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(increase(\n    process_cpu_seconds_total{component=\"sync\",group=\"$group\"}[1m]\n))",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}